### ISSUE TITLE
"Pas de données" au-dessus d'un certain numéro

### ISSUE THREAD

**Issue by pil0u** [QuentinAM/rules-browser#1]
Salut, il semblerait qu'il n'y ait pas de données à partir d'un certain numéro de carte alors qu'elles sont bien sorties. C'est un bug ou une feature :-) ?

**Comment by QuentinAM** [comment]
Bonjour, les cartes peuvent être sorties mais pas attribuées, par exemple, si j’ouvre un pack mais que je ne débloque pas les cartes, les cartes dedans seront quand meme sorties. Du coup le site les affichera comme sorties mais non attribues « pas de donnée ».

**Comment by pil0u** [comment]
Ok dans ce cas je pense que c'était un bug d'affichage de mon côté 👍
